apiVersion: apps/v1
kind: Deployment
metadata:
  name: travel-booking
  namespace: travel-booking
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: travel-booking
  template:
    metadata:
      labels:
        app: travel-booking
    spec:
      containers:
        - name: travel-booking
          image: travel_booking_devops_simple_fixed-travel-booking:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: travel-booking-config
            - secretRef:
                name: travel-booking-secret
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 20
            periodSeconds: 20
