"""empty message

Revision ID: 455e3f11998a
Revises: 
Create Date: 2024-10-11 16:06:03.859498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '455e3f11998a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flight', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_price', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.drop_column('price')

    with op.batch_alter_table('hotel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_price', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.drop_column('price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hotel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.FLOAT(), nullable=False))
        batch_op.drop_column('_price')

    with op.batch_alter_table('flight', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.FLOAT(), nullable=False))
        batch_op.drop_column('_price')

    # ### end Alembic commands ###
