"""empty message

Revision ID: 63567a03bc16
Revises: ed4120045e91
Create Date: 2024-10-11 16:24:36.526694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63567a03bc16'
down_revision = 'ed4120045e91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('package_deal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('package_deal', schema=None) as batch_op:
        batch_op.drop_column('price')

    # ### end Alembic commands ###
