"""empty message

Revision ID: 8ec0777c942d
Revises: 63567a03bc16
Create Date: 2024-10-15 09:22:49.298258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ec0777c942d'
down_revision = '63567a03bc16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flight', schema=None) as batch_op:
        batch_op.add_column(sa.Column('departure_time', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('arrival_time', sa.DateTime(), nullable=False))
        batch_op.drop_column('return_date')
        batch_op.drop_column('departure_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flight', schema=None) as batch_op:
        batch_op.add_column(sa.Column('departure_date', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('return_date', sa.DATETIME(), nullable=False))
        batch_op.drop_column('arrival_time')
        batch_op.drop_column('departure_time')

    # ### end Alembic commands ###
