"""empty message

Revision ID: ed4120045e91
Revises: 455e3f11998a
Create Date: 2024-10-11 16:07:03.693046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed4120045e91'
down_revision = '455e3f11998a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flight', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=False))
        batch_op.drop_column('_price')

    with op.batch_alter_table('hotel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=False))
        batch_op.drop_column('_price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hotel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_price', sa.NUMERIC(precision=10, scale=2), nullable=False))
        batch_op.drop_column('price')

    with op.batch_alter_table('flight', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_price', sa.NUMERIC(precision=10, scale=2), nullable=False))
        batch_op.drop_column('price')

    # ### end Alembic commands ###
